config/routes.rb
Rails.application.routes.draw do


  resources :measures

  resources :supersets
  resources :workouts
  resources :units
  resources :exercises

  resources :attendances do
    resources :performances
    resources :measurements
  end

  resources :training_sessions do
    resources :attendances  do
      resources :performances
    end
    resources :planned_workouts
  end
  resources :planned_workouts
  resources :performances

  resources :tariffs
  devise_for :users

  root to: 'dashboard#index'
  resources :users

  resources :clients do
    resources :payments
    member do
      get :search
    end
  end
  resources :measurements
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :unit
  has_many :supersets
  has_many :planned_workouts

  def to_s
    name
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @workouts = Workout.all
    respond_with(@workouts)
  end

  def show
    respond_with(@workout)
  end

  def new
    @workout = Workout.new
    respond_with(@workout)
  end

  def edit
  end

  def create
    @workout = Workout.new(workout_params)
    @workout.save
    respond_with(@workout)
  end

  def update
    @workout.update(workout_params)
    respond_with(@workout)
  end

  def destroy
    @workout.destroy
    respond_with(@workout)
  end

  private
    def set_workout
      @workout = Workout.find(params[:id])
    end

    def workout_params
      params.require(:workout).permit(:name, :unit_id, :description)
    end
end

app/views/workouts/_form.html.slim
= simple_form_for(@workout) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.association :unit
    = f.input :description

  .form-actions
    = f.button :submit

app/views/workouts/edit.html.slim
h1 Editing workout

== render 'form'

= link_to 'Show', @workout
'|
= link_to 'Back', workouts_path

app/views/workouts/index.html.slim
h1 Listing workouts

table
  thead
    tr
      th Name
      th Unit
      th Description
      th
      th
      th

  tbody
    - @workouts.each do |workout|
      tr
        td = workout.name
        td = workout.unit
        td = workout.description
        td = link_to 'Show', workout
        td = link_to 'Edit', edit_workout_path(workout)
        td = link_to 'Destroy', workout, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Workout', new_workout_path

app/views/workouts/new.html.slim
h1 New workout

== render 'form'

= link_to 'Back', workouts_path

app/views/workouts/show.html.slim
p#notice = notice

p
  strong Name:
  = @workout.name
p
  strong Unit:
  = @workout.unit
p
  strong Description:
  = @workout.description

= link_to 'Edit', edit_workout_path(@workout)
'|
= link_to 'Back', workouts_path