config/routes.rb
Rails.application.routes.draw do


  resources :measures

  resources :supersets
  resources :workouts
  resources :units
  resources :exercises

  resources :attendances do
    resources :performances
    resources :measurements
  end

  resources :training_sessions do
    resources :attendances  do
      resources :performances
    end
    resources :planned_workouts
  end
  resources :planned_workouts
  resources :performances

  resources :tariffs
  devise_for :users

  root to: 'dashboard#index'
  resources :users

  resources :clients do
    resources :payments
    member do
      get :search
    end
  end
  resources :measurements
end

app/models/training_session.rb
class TrainingSession < ActiveRecord::Base
  validates :starts_at, presence: true
  validates :minutes, presence: true, numericality: { only_integer: true, greater_than: 0}
  validates :location, presence: true
  validate :cannot_overlap_with_a_previously_saved_session

  has_many :attendances
  has_many :planned_workouts

#find a better name for minutes: duration, duration_in_minutes
  def ends_at
    starts_at + minutes.minutes
  end

  def overlaps?(other)
    (starts_at <= other.ends_at) && ( other.starts_at <= starts_at)
  end

  def to_s
    "Group Session on #{starts_at.to_s(:week_of_day_and_month_year)} from #{starts_at.to_s(:hours_and_minutes)} to #{ends_at.to_s(:hours_and_minutes)} at the #{location} "
  end

  private

  def cannot_overlap_with_a_previously_saved_session
    overlaps = TrainingSession.select {|ts| overlaps?(ts) && ts != self}.map(&:to_s)
    errors.add(:starts_at, "overlaps with another session #{overlaps}" ) if overlaps.any?
  end

end

app/controllers/training_sessions_controller.rb
class TrainingSessionsController < ApplicationController
  before_action :set_training_session, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @training_sessions = TrainingSession.order(starts_at: :desc).page params[:page]
  end

  def show
    respond_with(@training_session)
  end

  def new
    @training_session = TrainingSession.new
    respond_with(@training_session)
  end

  def edit
  end

  def create
    @training_session = TrainingSession.new(training_session_params)
    if @training_session.save
      flash[:notice] = 'Training Session has been scheduled.'
      redirect_to training_sessions_path
    else
      render :new
    end
  end

  def update
    flash[:notice] = 'Training Session has been updated.' if @training_session.update(training_session_params)
    respond_with(@training_session)
  end

  def destroy
    if @training_session.attendances.empty?
      @training_session.destroy
      respond_with(@training_session)
    else
      flash[:warning] = "You can not delete a training session with #{@training_session.attendances.count} participants."
      redirect_to training_sessions_path
    end
  end

  private
    def set_training_session
      @training_session = TrainingSession.find(params[:id])
    end

    def training_session_params
      params.require(:training_session).permit( :starts_at, :location, :minutes)
    end
end

app/views/training_sessions/_form.html.slim
= simple_form_for(@training_session, html: {class: 'form-horizontal'}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :starts_at, as: :datetime_picker
    = f.input :location
    = f.input :minutes
    = f.input :comments
  .form-actions
   = f.button :submit

app/views/training_sessions/edit.html.slim
h1 Editing Training Session

== render 'form'


= link_to 'Show', @training_session
'|
= link_to 'Back', training_sessions_path

app/views/training_sessions/index.html.slim
h1 Training Sessions

.btn.btn-success  = link_to 'Schedule New Training Session', new_training_session_path

table.table.table-striped
  = paginate(@training_sessions)
  thead
    tr
      th Start Date and Time
      th Minutes
      th Location
      th Participants
      th
      th

  tbody
    - @training_sessions.each do |training_session|
      tr[id="training_session_#{training_session.id}"]
        td = training_session.starts_at.to_s(:long)
        td = training_session.minutes
        td = training_session.location
        td = training_session.attendances.count
        td = link_to 'Show', training_session
        td = link_to 'Edit', edit_training_session_path(training_session)
        td = link_to 'Destroy', training_session, data: {:confirm => 'Are you sure?'}, :method => :delete

br

app/views/training_sessions/new.html.slim
h1 New training session

= render 'form'

= link_to 'Back', training_sessions_path

app/views/training_sessions/show.html.slim
.container
  .row
    .col-xs-9
      p
        strong
          = @training_session.to_s
    .col-xs-3
      = link_to 'Edit', edit_training_session_path(@training_session)
      '|
      = link_to 'Back', training_sessions_path
  .row
    .col-xs-6
      strong Workouts
      = link_to 'New workout', new_training_session_planned_workout_path(@training_session)
    .col-xs-6
      = render @training_session.planned_workouts
  .row
    .col-xs-6
      = link_to "Take Measurements"
  .row
    .col-xs-8 = "#{@training_session.attendances.count} Participants"
  .col-xs-12
    table.table.table-striped.table-hover
      thead
        tr
          th
            | Participants
          th
            .btn
              = link_to 'Add Participant', new_training_session_attendance_path([@training_session])
      tbody
          tr
            td = render @training_session.attendances