config/routes.rb
Rails.application.routes.draw do


  resources :measures

  resources :supersets
  resources :workouts
  resources :units
  resources :exercises

  resources :attendances do
    resources :performances
    resources :measurements
  end

  resources :training_sessions do
    resources :attendances  do
      resources :performances
    end
    resources :planned_workouts
  end
  resources :planned_workouts
  resources :performances

  resources :tariffs
  devise_for :users

  root to: 'dashboard#index'
  resources :users

  resources :clients do
    resources :payments
    member do
      get :search
    end
  end
  resources :measurements
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
  belongs_to :attendance
  belongs_to :measure

  def to_s
   "Weight: #{weight} Waist: #{waist} Hip: #{hip} Bicep: #{bicep} Thigh: #{thigh}"
  end
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  before_action :set_attendance, only: [:index, :new, :create]
  before_action :set_measurement, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @measurements = @attendance.measurements.all
    respond_with(@measurements)
  end

  def show
    respond_with(@measurement)
  end

  def new
    @measurement = @attendance.measurements.build
  end

  def edit
  end

  def create
    @measurement = @attendance.measurements.build(measurement_params)
    if @measurement.save
      redirect_to @attendance.training_session
    else
      flash[:error] = "Measurement not taken"
      render :new
    end
  end

  def update
    if @measurement.update(measurement_params)
      redirect_to @measurement.attendance.training_session
    else
      flash[:error] = "Measurement not updated"
      redirect_to @measurement.attendance.training_session
    end
  end

  def destroy
    training_session = @measurement.attendance.training_session
    @measurement.destroy
    redirect_to training_session
  end

  private
    def set_attendance
      @attendance = Attendance.find(params[:attendance_id])
    end

    def set_measurement
      @measurement = Measurement.find(params[:id])
    end

    def measurement_params
      params.require(:measurement).permit(:attendance_id, :weight, :waist, :hip, :bicep, :thigh)
    end
end

app/views/measurements/_form.html.slim
= simple_form_for([@attendance, @measurement]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :weight, label: 'Weight (kgs)'
    = f.input :waist, label: 'Waist (cms)'
    = f.input :hip , label: 'Hip (cms)'
    = f.input :bicep, label: "Bicep (cms)"
    = f.input :thigh, label: "Thigh (cms)"

  .form-actions
    = f.button :submit

app/views/measurements/_measurement.html.slim
.col-xs-10
  = measurement.to_s
.col-xs-1
  = link_to "Edit", edit_measurement_path(measurement)
.col-xs-1
= link_to 'Destroy', measurement, method: :delete

app/views/measurements/edit.html.slim
h1 Editing measurement

== render 'form'

= link_to 'Show', @measurement
'|
= link_to 'Back', measurements_path

app/views/measurements/index.html.slim
h1 Listing measurements

table
  thead
    tr
      th Attendance
      th Measure
      th Score
      th
      th
      th

  tbody
    - @measurements.each do |measurement|
      tr
        td = measurement.attendance
        td = measurement.measure
        td = measurement.score
        td = link_to 'Show', measurement
        td = link_to 'Edit', edit_measurement_path(measurement)
        td = link_to 'Destroy', measurement, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Measurement', new_measurement_path

app/views/measurements/new.html.slim
h1 New Measurement

= render 'form'

app/views/measurements/show.html.slim
p#notice = notice

p
  strong Attendance:
  = @measurement.attendance
p
  strong Measure:
  = @measurement.measure
p
  strong Score:
  = @measurement.score

= link_to 'Edit', edit_measurement_path(@measurement)
'|
= link_to 'Back', measurements_path