config/routes.rb
Rails.application.routes.draw do


  resources :measures

  resources :supersets
  resources :workouts
  resources :units
  resources :exercises

  resources :attendances do
    resources :performances
    resources :measurements
  end

  resources :training_sessions do
    resources :attendances  do
      resources :performances
    end
    resources :planned_workouts
  end
  resources :planned_workouts
  resources :performances

  resources :tariffs
  devise_for :users

  root to: 'dashboard#index'
  resources :users

  resources :clients do
    resources :payments
    member do
      get :search
    end
  end
  resources :measurements
end

app/models/unit.rb
class Unit < ActiveRecord::Base

  def to_s
    acronym
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @units = Unit.all
    respond_with(@units)
  end

  def show
    respond_with(@unit)
  end

  def new
    @unit = Unit.new
    respond_with(@unit)
  end

  def edit
  end

  def create
    @unit = Unit.new(unit_params)
    @unit.save
    respond_with(@unit)
  end

  def update
    @unit.update(unit_params)
    respond_with(@unit)
  end

  def destroy
    @unit.destroy
    respond_with(@unit)
  end

  private
    def set_unit
      @unit = Unit.find(params[:id])
    end

    def unit_params
      params.require(:unit).permit(:acronym, :description)
    end
end

app/views/units/_form.html.slim
= simple_form_for(@unit) do |f|
  = f.error_notification

  .form-inputs
    = f.input :acronym
    = f.input :description

  .form-actions
    = f.button :submit

app/views/units/edit.html.slim
h1 Editing unit

== render 'form'

= link_to 'Show', @unit
'|
= link_to 'Back', units_path

app/views/units/index.html.slim
h1 Listing units

table
  thead
    tr
      th Acronym
      th Description
      th
      th
      th

  tbody
    - @units.each do |unit|
      tr
        td = unit.acronym
        td = unit.description
        td = link_to 'Show', unit
        td = link_to 'Edit', edit_unit_path(unit)
        td = link_to 'Destroy', unit, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Unit', new_unit_path

app/views/units/new.html.slim
h1 New unit

== render 'form'

= link_to 'Back', units_path

app/views/units/show.html.slim
p#notice = notice

p
  strong Acronym:
  = @unit.acronym
p
  strong Description:
  = @unit.description

= link_to 'Edit', edit_unit_path(@unit)
'|
= link_to 'Back', units_path